name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal
    - name: Install rust stable
      run: rustup install stable && rustup default stable
    - name: Install cobalt
      run: cargo install cobalt-bin

    - uses: actions/checkout@v2

    - name: Check that build is up to date
      run: rm -rf _site/ && cobalt build && git diff --exit-code
